### ISSUE TITLE
Toxic Members

### ISSUE THREAD

**Issue by AryanJ-NYC** [mozillascience/leadership-training#9]
At the top of [Toxic Members](http://mozillascience.github.io/leadership-training/04.2-toxic_members.html), it reads:

> // rewrite this stuff copied from - https://etherpad.mozilla.org/Portland-Community-Building
>  Exactly what "stuff" should be copied?

**Comment by abbycabs** [comment]
The entire thing is copied from that etherpad! I was thinking it might work better as prose than copied points from a talk.

**Comment by AryanJ-NYC** [comment]
Is there more to be added?

**Comment by abbycabs** [comment]
If you have more to say, I welcome additional content! The notes were a starting point :)

**Comment by AryanJ-NYC** [comment]
Oh! Understood. I thought the top meant that you'd like additional content from the Etherpad to the page.
